services:
  minecraft:
    build:
      context: .
      args:
        - JAVA_VERSION=26
        - SPIGOT_VERSION=26.1.2
        - EULA=true
        - USER_UID=1000
        - USER_GID=1000
    environment:
      - MINRAM=${MINRAM-2G}
      - MAXRAM=${MAXRAM-16G}
      - SHUTDOWN_PORT=${SHUTDOWN_PORT-20563}
      - WORLD_PATH=${WORLD_PATH-data}
    restart: unless-stopped
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true
    volumes:
      - data:/server/data
      - config:/server/config
      - plugins:/server/plugins

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/projects/${COMPOSE_PROJECT_NAME}/data"
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/projects/${COMPOSE_PROJECT_NAME}/config"
  plugins:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/projects/${COMPOSE_PROJECT_NAME}/plugins"
